version: '2'
services:
  db:
    image: postgres:13
    # container_name: postgres13
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo14:
    image: odoo:14
    # container_name: odoo14
    depends_on:
      - db
    ports:
      - "10014:8069"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/custom_module
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
# fix for: ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
# happens sometimes when your laptop vpn services use same addresses as docker network
# if this creates any type of error, just comment out everything. It will still work with the default network & default id addresses
networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.57.0/24